### ISSUE TITLE
Opmaak info button

### ISSUE THREAD

**Issue by Stefan-Espant** [OvenMagnetron/fix-the-flow-wireflow#10]
Kijk of je de uitlijning van je icon met tekst kan opmaken.

Bijvoorbeeld:

```css
  display: flex;
  align-items: center;
  justify-content: space-around;
```

https://github.com/OvenMagnetron/fix-the-flow-wireflow/blob/faa6f87754d4e07f9d16250d56fb174b282ec093/styles/style.css#L376

**Comment by OvenMagnetron** [comment]
Dit is niet doorgevoerd, i.v.m. buggen van buttons. E.v.t. wordt hier later nog naar gekeken.
