### ISSUE TITLE
Interactie met display none

### ISSUE THREAD

**Issue by Stefan-Espant** [OvenMagnetron/fix-the-flow-wireflow#13]
Gaaf dat de sectie verdwijnt wanneer je op input drukt. Zou je dit kunnen animeren? 
De interactie is er al, maar hoe maak je dit aantrekkelijk voor de gebruiker?

https://github.com/OvenMagnetron/fix-the-flow-wireflow/blob/faa6f87754d4e07f9d16250d56fb174b282ec093/scripts/script.js#L22

**Comment by OvenMagnetron** [comment]
Deze interactie is aangepast.
