### ISSUE TITLE
Feedback van de tweedejaars

### ISSUE THREAD

**Issue by Stefan-Espant** [OvenMagnetron/fix-the-flow-wireflow#9]
**Top:**
* Goed dat je gebruik maakt van verschillende stiftdiktes. 
* Duidelijke wireflow, ik weet waar ik naar kijk en wat ik kan verwachten straks in code

**Tip:**
* Probeer met het schetsen van afbeeldingen het gebruik van kaders met kruizen te vermijden. Dit biedt vaak niet veel context waar de afbeelding over gaat. Probeer een abstract beeld te tekenen. Dat biedt voor een ander meer info. 
* Probeer de juiste iconen te gebruiken voor je zoekknop
Bekijk deze website eens:
https://tabler-icons.io/
* Als je een box met tekst schetst, schrijf eerst de tekst en teken vervolgens het kader erom heen.
* Maak van je h2 "Waar bent u naar op zoek?" een label omdat het betrekking heeft op je inputveld

**Comment by OvenMagnetron** [comment]
Dit is allemaal toegepast. Bedankt voor de feedback.
